# Site settings
title: Polymer Blog
description: "The latest goings-on with the Polymer project and in the community. We'll update the blog to announce major releases and showcase cool stuff being built with Polymer."
baseurl: ""
url: "http://blog.polymer-project.org"
twitter_username: polymer
github_username:  polymer
feed_url: "http://blog.polymer-project.org/feed.xml"
add_permalinks: true
paginate: 5

exclude: ["node_modules", "sass", "app.yaml", "README.md",
          "CONTRIBUTING.md", "Gruntfile.js", "package.json", "config.rb",
          "build.py", "polymer-all", "components"]

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

# Authors
authors:
    polymer-team:
        display_name: polymer team
        github: Polymer
    taylor:
        display_name: Taylor Savage
        github: tjsavage
    jeffy:
        display_name: Jeff Posnick
        github: jeffposnick
    arthur:
        display_name: arthur
        github: arthurevans
    rob:
        display_name: rob
        github: robdodson

# Serve settings
# detach: true
